### PR TITLE
LastEditingNumericValue should be as same as Value when ValueChanged

### PR DESCRIPTION
**Pull request by heartacker**

### CODE REVIEW

**Comment by heartacker** [comment]
also fix https://github.com/Dirkster99/NumericUpDownLib/issues/52 by revert

**Comment by ClourneySemi** [comment]
@Dirkster99 thanks，and could U please help to merge this

**Comment by heartacker** [comment]
@heartacker @Dirkster99 hi, Could you please help to merge this pr and release a new nugget version, my project needs this bug-fixed indeedly.
thanks

**Comment by Dirkster99** [comment]
Please do not change the libraries version on a branch, thank you

**Comment by heartacker** [comment]
> Please do not change the libraries version on a branch, thank you

thanks very much. my bug has fixed.

and I will do not changing that next time if there is pr.

really thank you

**Comment by Dirkster99** [comment]
You are more than welcome since you've put in all the hard work to improve it :-)

**Pull request merged**
